#!/bin/bash
# Run xidlehook
xidlehook --not-when-fullscreen --not-when-audio --timer 10 'light -S 10' 'light -S 50' --timer 10 'light -S 50; betterlockscreen -l' '' --timer 3600 'systemctl suspend' ''
