#!/bin/zsh

echo "Starting system update & cleanup"

sudo dnf update

sudo snap refresh

sudo flatpak update

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

echo

sudo dnf clean dbcache

sudo fwupdmgr refresh

sudo fwupdmgr update

echo "Finished system update & cleanup"
